"""DefectTrack IssueTracker adapter — scaffold generated by Teacher LLM.

Complete all TODO: markers using the spec at:
    <env_dir>/input/api-specs/<SYS0>_API_Documentation.md

Then run contract tests:
    pytest customizations/issue_tracker/tests/test_contract.py \
        --adapter defecttrack --project <any_string> -v

Expected contract results (known API gaps):
    passed=7  failed=3  fail_methods=C02,C07,C08
    C02 — no update endpoint in API
    C07 — no search/list endpoint in API
    C08 — no changelog endpoint in API

Required env vars:
    HILDA_DEFECTTRACK_BASE_URL     https://<real-host>/api/v1/sync/ticketengine
    HILDA_DEFECTTRACK_SYSTEM_NAME  <SYS0> path segment (fill from spec)
    HILDA_DEFECTTRACK_AUTH_PARAM   <COL0> query parameter name (fill from spec)
    HILDA_DEFECTTRACK_AUTH_VALUE   actual auth token (from credential_service in prod)
    HILDA_DEFECTTRACK_RESOLVE_STATUS   resolveStatus default value (fill from spec)
    HILDA_DEFECTTRACK_RESOLVED_LAYER   resolvedLayer default value (fill from spec)
"""
from __future__ import annotations

import os
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import AsyncIterator

import httpx

from core.src.diagnostics.error_codes import PipelineError
from core.src.issue_tracker.protocol import (
    AttachmentInput,
    AttachmentRef,
    CommentRef,
    Issue,
    IssueChange,
    IssueQuery,
    IssueRef,
    IssuePriority,
    IssueStatus,
    WebhookRef,
)


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class DefectTrackConfig:
    base_url: str         # https://<real-host>/api/v1/sync/ticketengine
    system_name: str      # TODO: <SYS0> literal used in URL path segments
    auth_param_name: str  # TODO: <COL0> query parameter name
    auth_param_value: str # runtime secret — loaded from env, never committed
    resolve_status: str   # TODO: valid resolveStatus value from spec
    resolved_layer: str   # TODO: valid resolvedLayer value from spec
    resolve_reason: str = "Resolved via HILDA"
    resolve_countermeasure: str = "See HILDA tracker"

    @classmethod
    def from_env(cls, prefix: str = "HILDA_DEFECTTRACK_") -> "DefectTrackConfig":
        def _require(name: str) -> str:
            val = os.environ.get(f"{prefix}{name}")
            if not val:
                raise PipelineError(
                    "ITR-E006",
                    context={"slug": f"defecttrack (missing env var {prefix}{name})"},
                )
            return val

        return cls(
            base_url=_require("BASE_URL").rstrip("/"),
            system_name=_require("SYSTEM_NAME"),
            auth_param_name=_require("AUTH_PARAM"),
            auth_param_value=_require("AUTH_VALUE"),
            resolve_status=_require("RESOLVE_STATUS"),
            resolved_layer=_require("RESOLVED_LAYER"),
        )


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------


class DefectTrackAdapter:
    """IssueTracker adapter for the <SYS0> defect tracking system.

    Known gaps vs. full IssueTracker Protocol — contract failures are expected:
      update_issue       — no update endpoint; raises ITR-E007       (C02 fails)
      search             — no list/search endpoint; returns empty     (C07 fails)
      list_recent_changes — no changelog endpoint; returns empty      (C08 fails)
      poll_changes       — no list endpoint; returns empty
      register_webhook   — not supported; raises ITR-W002
      status_field       — not in API response; tracked in-process
      timestamps         — not in API response; set to current time
    """

    def __init__(self, config: DefectTrackConfig) -> None:
        self._cfg = config
        self._http = httpx.AsyncClient(
            base_url=config.base_url,
            timeout=httpx.Timeout(30.0),
        )
        self._idempotency: dict[str, IssueRef] = {}
        self._comment_idempotency: dict[str, CommentRef] = {}
        # Status is not returned by the API — track transitions in-process.
        self._status_cache: dict[str, IssueStatus] = {}

    @property
    def source_system(self) -> str:
        return "defecttrack"

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _qp(self) -> dict[str, str]:
        """Auth query params appended to every request."""
        return {self._cfg.auth_param_name: self._cfg.auth_param_value}

    def _sys(self) -> str:
        return self._cfg.system_name

    def _make_ref(self, defect_code: str) -> IssueRef:
        return IssueRef(
            issue_id=defect_code,
            source_system=self.source_system,
            url=f"{self._cfg.base_url}/get/{self._sys()}/ticket/{defect_code}",
        )

    def _raise_for_error(self, resp: httpx.Response, issue_id: str = "") -> None:
        if resp.status_code == 401:
            raise PipelineError("ITR-E001", context={"system": "defecttrack"})
        if resp.status_code == 404:
            raise PipelineError(
                "ITR-E002", context={"issue_id": issue_id, "system": "defecttrack"}
            )
        if resp.status_code == 409:
            raise PipelineError(
                "ITR-E003", context={"key": issue_id, "existing_id": issue_id}
            )
        if resp.status_code == 429:
            raise PipelineError(
                "ITR-W001", context={"system": "defecttrack", "retry_after_s": "60"}
            )
        resp.raise_for_status()

    # ------------------------------------------------------------------
    # Protocol implementation
    # ------------------------------------------------------------------

    async def create_issue(
        self,
        project: str,
        summary: str,
        description: str,
        fields: dict | None = None,
        attachments: list[AttachmentInput] | None = None,
        idempotency_key: str | None = None,
        timeout_s: float | None = None,
    ) -> IssueRef:
        if idempotency_key and idempotency_key in self._idempotency:
            return self._idempotency[idempotency_key]

        body: dict = {
            "title": summary,        # TODO: confirm request field name from spec
            "description": description,  # TODO: confirm request field name from spec
            # TODO: add any other required fields (e.g. project, priority, component)
        }
        if fields:
            body.update(fields)

        resp = await self._http.post(
            f"/create/{self._sys()}/ticket",
            json=body,
            params=self._qp(),
        )
        self._raise_for_error(resp)

        data = resp.json()
        # TODO: confirm response field name — spec says id_field = defectCode
        defect_code = str(
            data.get("defectCode")  # TODO: verify this field name in actual response
            or data.get("id")
            or ""
        )
        if not defect_code:
            raise PipelineError(
                "ITR-E006",
                context={"slug": "defecttrack (create response missing defectCode)"},
            )

        ref = self._make_ref(defect_code)
        self._status_cache[defect_code] = IssueStatus.OPEN
        if idempotency_key:
            self._idempotency[idempotency_key] = ref
        return ref

    async def get_issue(
        self, ref: IssueRef, timeout_s: float | None = None
    ) -> Issue:
        resp = await self._http.get(
            f"/get/{self._sys()}/ticket/{ref.issue_id}",
            params=self._qp(),
        )
        self._raise_for_error(resp, ref.issue_id)

        data = resp.json()
        # TODO: verify all field names below against actual API response
        priority_raw = data.get("priority")  # TODO: confirm field name + value vocab
        priority: IssuePriority | None = None
        if priority_raw:
            try:
                priority = IssuePriority(str(priority_raw).capitalize())
            except ValueError:
                pass

        now = datetime.now(timezone.utc)
        return Issue(
            ref=ref,
            summary=data.get("title", ""),        # TODO: confirm field name
            description=data.get("description"),   # TODO: confirm field name
            status=self._status_cache.get(ref.issue_id, IssueStatus.OPEN),
            priority=priority,
            assignee=None,   # not in API response
            labels=[],
            created_at=now,  # not in API response
            updated_at=now,  # not in API response
        )

    async def update_issue(
        self, ref: IssueRef, updates: dict, timeout_s: float | None = None
    ) -> None:
        # No update endpoint in this API.
        raise PipelineError(
            "ITR-E007",
            context={"operation": "update_issue", "adapter": "defecttrack"},
        )

    async def transition_issue(
        self, ref: IssueRef, transition: str, timeout_s: float | None = None
    ) -> None:
        t = transition.lower()

        if t in ("resolve", "done"):
            body = {
                "reason": self._cfg.resolve_reason,
                "countermeasure": self._cfg.resolve_countermeasure,
                "resolveStatus": self._cfg.resolve_status,  # TODO: confirm field name + value
                "resolvedLayer": self._cfg.resolved_layer,  # TODO: confirm field name + value
                # TODO: add any other required fields from resolve endpoint spec
            }
            resp = await self._http.put(
                f"/resolve/{self._sys()}/defect/{ref.issue_id}",
                json=body,
                params=self._qp(),
            )
            self._raise_for_error(resp, ref.issue_id)
            self._status_cache[ref.issue_id] = IssueStatus.RESOLVED

        elif t == "close":
            resp = await self._http.put(
                f"/close/{self._sys()}/defect/{ref.issue_id}",
                params=self._qp(),
                # TODO: check if close endpoint requires a request body
            )
            self._raise_for_error(resp, ref.issue_id)
            self._status_cache[ref.issue_id] = IssueStatus.CLOSED

        else:
            raise PipelineError(
                "ITR-E004",
                context={"transition": transition, "issue_id": ref.issue_id},
            )

    async def close_issue(
        self, ref: IssueRef, resolution: str, timeout_s: float | None = None
    ) -> None:
        if self._status_cache.get(ref.issue_id) == IssueStatus.CLOSED:
            return  # idempotent

        resp = await self._http.put(
            f"/close/{self._sys()}/defect/{ref.issue_id}",
            params=self._qp(),
            # TODO: check if close endpoint requires a request body
        )
        self._raise_for_error(resp, ref.issue_id)
        self._status_cache[ref.issue_id] = IssueStatus.CLOSED

    async def add_comment(
        self,
        ref: IssueRef,
        body: str,
        attachments: list[AttachmentInput] | None = None,
        idempotency_key: str | None = None,
        timeout_s: float | None = None,
    ) -> CommentRef:
        if idempotency_key and idempotency_key in self._comment_idempotency:
            return self._comment_idempotency[idempotency_key]

        # TODO: confirm request body field name for comment text
        payload = {
            "comment": body,  # TODO: verify field name from spec
            # TODO: add any other required fields
        }
        resp = await self._http.post(
            f"/add/{self._sys()}/comment/{ref.issue_id}",
            json=payload,
            params=self._qp(),
        )
        self._raise_for_error(resp, ref.issue_id)

        # TODO: confirm whether response contains a comment ID field
        data = resp.json() if resp.content else {}
        comment_id = str(
            data.get("commentId")  # TODO: verify field name
            or data.get("id")
            or uuid.uuid4()
        )

        cref = CommentRef(
            comment_id=comment_id,
            issue_ref=ref,
            source_system=self.source_system,
        )
        if idempotency_key:
            self._comment_idempotency[idempotency_key] = cref
        return cref

    async def upload_attachment(
        self, ref: IssueRef, file: AttachmentInput, timeout_s: float | None = None
    ) -> AttachmentRef:
        if isinstance(file, Path):
            filename = file.name
            content = file.read_bytes()
        else:
            chunks: list[bytes] = []
            async for chunk in file:  # type: ignore[union-attr]
                chunks.append(chunk)
            content = b"".join(chunks)
            filename = "attachment"

        # Spec says: multipart_form, field name = "file"
        files = {"file": (filename, content, "application/octet-stream")}
        resp = await self._http.post(
            f"/upload/{self._sys()}/file/{ref.issue_id}",
            files=files,
            params=self._qp(),
        )
        self._raise_for_error(resp, ref.issue_id)

        # TODO: confirm whether response contains an attachment ID field
        data = resp.json() if resp.content else {}
        attachment_id = str(
            data.get("fileId")    # TODO: verify field name
            or data.get("id")
            or uuid.uuid4()
        )

        return AttachmentRef(
            attachment_id=attachment_id,
            issue_ref=ref,
            filename=filename,
            source_system=self.source_system,
        )

    async def search(
        self, query: IssueQuery, timeout_s: float | None = None
    ) -> AsyncIterator[IssueRef]:
        # No search/list endpoint in this API. C07 contract check will fail — expected.
        async def _empty() -> AsyncIterator[IssueRef]:
            return
            yield  # pragma: no cover

        return _empty()

    async def list_recent_changes(
        self, ref: IssueRef, since: datetime, timeout_s: float | None = None
    ) -> AsyncIterator[IssueChange]:
        # No changelog endpoint in this API. C08 contract check will fail — expected.
        async def _empty() -> AsyncIterator[IssueChange]:
            return
            yield  # pragma: no cover

        return _empty()

    async def register_webhook(
        self,
        callback_url: str,
        events: list[str],
        secret: str,
        timeout_s: float | None = None,
    ) -> WebhookRef:
        raise PipelineError("ITR-W002", context={"system": "defecttrack"})

    async def poll_changes(
        self, since: datetime, timeout_s: float | None = None
    ) -> AsyncIterator[IssueChange]:
        # No list endpoint — cannot poll. hilda-beat skips this adapter.
        async def _empty() -> AsyncIterator[IssueChange]:
            return
            yield  # pragma: no cover

        return _empty()


# ---------------------------------------------------------------------------
# Factory — required by load_adapter('defecttrack')
# ---------------------------------------------------------------------------


def make_adapter(config: dict | None = None) -> DefectTrackAdapter:
    """Load config from environment and return a ready adapter instance."""
    return DefectTrackAdapter(DefectTrackConfig.from_env())
